version: "3"
services:
  hospitalDB:
    image: mysql/mysql-server:5.7
    networks:
      - hospital-mysql
    container_name: hospitalDB
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=health
    volumes:
      - /data/mysql
  hospital-service:
    image: hospital-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    links:
      - hospitalDB
    environment:
      - DATABASE_HOST=hospitalDB
      - DATABASE_USER=root
      - DATABASE_PASSWORD=1234
      - DATABASE_NAME=health
      - DATABASE_PORT=3306
    networks:
      - hospital-mysql
    depends_on:
      - hospitalDB
networks:
  hospital-mysql: