server:
  port: 8075

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

turbine:
  appConfig: hospital-service, department-service, patient-service
  clusterNameExpression: "'default'"
  #clusterNameExpression: new String("default")





